name: "surrealdb-migrations"
description: "Apply migrations to a SurrealDB instance"
author: "Odonno"
branding:
  icon: "arrow-up-circle"
  color: "purple"

runs:
  using: "node18"
  main: "dist/index.js"

inputs:
  version:
    description: "The version of surrealdb-migrations to install"
    required: true
    default: "latest"

  args:
    description: "Extra command line arguments passed to surrealdb-migrations"
    required: false
