name: "surrealdb-migrations"
description: "Apply migrations to a SurrealDB instance"
author: "Odonno"
branding:
  icon: "arrow-up-circle"
  color: "purple"

runs:
  using: "node16"
  main: "dist/index.js"

inputs:
  version:
    description: "The version of surrealdb-migrations to install"
    required: true
    default: "latest"

  url:
    description: "Url of the surrealdb instance"
    required: false

  ns:
    description: "Namespace to use inside the surrealdb instance"
    required: false

  db:
    description: "Name of the database to use inside the surrealdb instance"
    required: false

  username:
    description: "Username used to authenticate to the surrealdb instance"
    required: false

  password:
    description: "Password used to authenticate to the surrealdb instance"
    required: false
