name: "surrealdb-migrations"
description: "Apply migrations to a SurrealDB instance"
author: "Odonno"
branding:
  icon: "arrow-up-circle"
  color: "purple"

runs:
  using: "node16"
  main: "dist/index.js"

inputs:
  version:
    description: "The version of surrealdb-migrations to install"
    required: true
    default: "latest"

  address:
    description: "Address of the surrealdb instance"
    required: false

  ns:
    description: "Namespace to use inside the surrealdb instance"
    required: false

  db:
    description: "Name of the database to use inside the surrealdb instance"
    required: false

  username:
    description: "Username used to authenticate to the surrealdb instance"
    required: false

  password:
    description: "Password used to authenticate to the surrealdb instance"
    required: false

  skip-untracked-files:
    description: "When a schema changes is made, it should create a definition file when applying migrations. If we detect untracked definition files, the CI will fail. Set to `true` to skip untracked files."
    required: false
    default: false
