name: Continuous integration

on: [pull_request, push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: Create npm configuration
        run: echo -e "\n//npm.pkg.github.com/:_authToken=${token}" >> .npmrc
        env:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
